#include "DBoW3/DBoW3.h"                  // 引入 DBoW3 库，用于加载词典、计算 BoW 向量和建立数据库
#include <opencv2/core/core.hpp>          // 引入 OpenCV 核心模块，提供 Mat 等基础数据结构
#include <opencv2/highgui/highgui.hpp>    // 引入 OpenCV 图像读写相关接口，例如 imread
#include <opencv2/features2d/features2d.hpp> // 引入 OpenCV 特征模块，用于提取 ORB 特征
#include <iostream>                       // 引入标准输入输出流，用于 cout/cerr 打印信息
#include <vector>                         // 引入 vector 容器，用于保存图像和描述子
#include <string>                         // 引入 string 字符串类型，用于拼接图像路径

using namespace cv;                       // 使用 OpenCV 命名空间，简化 Mat、ORB 等类型写法
using namespace std;                      // 使用标准库命名空间，简化 cout、vector、string 等写法

/***************************************************
 * 本节演示了如何根据前面训练的字典计算相似性评分
 * ************************************************/
int main(int argc, char **argv) {         // 程序入口，argc/argv 此处未使用
    // read the images and database
    cout << "reading database" << endl;   // 提示开始读取视觉词典文件
    DBoW3::Vocabulary vocab("./vocabulary.yml.gz"); // 从本地加载之前训练好的小词典
    // DBoW3::Vocabulary vocab("./vocab_larger.yml.gz");  // 如需使用大词典，可改为加载 vocab_larger.yml.gz
    if (vocab.empty()) {                  // 检查词典是否成功加载
        cerr << "Vocabulary does not exist." << endl; // 如果词典为空，输出错误信息
        return 1;                         // 返回非零值表示程序异常结束
    }
    cout << "reading images... " << endl; // 提示开始读取待比较图像
    vector<Mat> images;                   // 保存所有待检测回环的图像
    for (int i = 0; i < 10; i++) {        // 依次读取 data 目录下编号 1 到 10 的图像
        string path = "./data/" + to_string(i + 1) + ".png"; // 根据编号拼接当前图像路径
        images.push_back(imread(path));   // 读取当前图像并加入 images 容器
    }

    // NOTE: in this case we are comparing images with a vocabulary generated by themselves, this may lead to overfit.
    // 注意：这里用同一批图像训练词典并做相似度比较，实验效果可能存在过拟合。
    // detect ORB features
    cout << "detecting ORB features ... " << endl; // 提示开始提取 ORB 特征
    Ptr<Feature2D> detector = ORB::create(); // 创建 ORB 特征检测器和描述子计算器
    vector<Mat> descriptors;             // 保存每张图像的 ORB 描述子
    for (Mat &image:images) {            // 遍历所有待读取相似度的图像
        vector<KeyPoint> keypoints;      // 保存当前图像检测到的关键点
        Mat descriptor;                  // 保存当前图像计算得到的描述子
        detector->detectAndCompute(image, Mat(), keypoints, descriptor); // 对当前图像提取 ORB 关键点和描述子
        descriptors.push_back(descriptor); // 将当前图像描述子保存起来，供后续 BoW 转换和数据库查询使用
    }

    // we can compare the images directly or we can compare one image to a database
    // 可以直接两两比较图像，也可以把图像加入数据库后再查询相似图像。
    // images :
    cout << "comparing images with images " << endl; // 提示开始进行图像之间的直接相似度比较
    for (int i = 0; i < images.size(); i++) { // 外层循环选择第一张待比较图像
        DBoW3::BowVector v1;             // 创建第一张图像的词袋向量
        vocab.transform(descriptors[i], v1); // 将第 i 张图像的 ORB 描述子转换为 BoW 向量
        for (int j = i; j < images.size(); j++) { // 内层循环选择第二张待比较图像，从 i 开始避免重复比较
            DBoW3::BowVector v2;         // 创建第二张图像的词袋向量
            vocab.transform(descriptors[j], v2); // 将第 j 张图像的 ORB 描述子转换为 BoW 向量
            double score = vocab.score(v1, v2); // 计算两个 BoW 向量之间的相似度得分
            cout << "image " << i << " vs image " << j << " : " << score << endl; // 输出两张图像的相似度
        }
        cout << endl;                    // 每完成一行比较后输出空行，便于阅读结果
    }

    // or with database
    cout << "comparing images with database " << endl; // 提示开始使用 DBoW3 数据库进行图像检索
    DBoW3::Database db(vocab, false, 0); // 用已有词典创建数据库；false 表示不使用直接索引，0 表示直接索引层级参数
    for (int i = 0; i < descriptors.size(); i++) // 遍历所有图像描述子
        db.add(descriptors[i]);          // 将当前图像描述子加入数据库
    cout << "database info: " << db << endl; // 输出数据库统计信息
    for (int i = 0; i < descriptors.size(); i++) { // 依次用每张图像作为查询图像
        DBoW3::QueryResults ret;         // 保存数据库查询返回的候选匹配结果
        db.query(descriptors[i], ret, 4);      // 查询与当前图像最相似的前 4 个结果
        cout << "searching for image " << i << " returns " << ret << endl << endl; // 输出当前查询图像的检索结果
    }
    cout << "done." << endl;             // 提示回环相似度实验完成
}                                        // main 函数结束
